FORMAT: 1A
HOST: http://localhost:8080

# venditto-server API

<!-- include(access.apib) -->
<!-- include(address.apib) -->
<!-- include(brand.apib) -->
<!-- include(category.apib) -->
<!-- include(item.apib) -->
<!-- include(order.apib) -->
<!-- include(order_problem.apib) -->
<!-- include(product.apib) -->
<!-- include(provider.apib) -->
<!-- include(user.apib) -->
